### ISSUE TITLE
Global Parameter model missing

### ISSUE THREAD

**Issue by hansstammler** [hansstammler/DECIDE#3]
We need to initialize the global parameters. 
Specified in the instruction PDF.

**Comment by simonsimon006** [comment]
We also need a class like e.g. Points to represent the 3D coordinates. Should we just make a Points class?

**Comment by hansstammler** [comment]
> We also need a class like e.g. Points to represent the 3D coordinates. Should we just make a Points class?

Yes, very good

**Comment by simonsimon006** [comment]
I will get started on it then.

**Comment by JesperSlagarp** [comment]
We probably want to use doubles/floats for the coordinates, not integers.

**Comment by simonsimon006** [comment]
Good point!
