### ISSUE TITLE
LIC 8 test gives error

### ISSUE THREAD

**Issue by gustafssonlinnea** [hansstammler/DECIDE#31]
LIC8IsCorrect() does not work properly, get FAILURE when trying to build. Error message:

error: constructor Point in class Point cannot be applied to given types;
        Point[] points2 = {new Point(1, 0), new Point(2.5, 0), new Point(3, 0), new Point(3, 0, new Point(3, 0))};

**Comment by simonsimon006** [comment]
Should be resolved after the last pull.
