### ISSUE TITLE
Three main test cases

### ISSUE THREAD

**Issue by hansstammler** [hansstammler/DECIDE#50]
After the entire program is complete mane sure the three main tests are there and accurate.

The inputs produce a "positive" result; in Assignment 1, this could mean that a launch is enabled.
The inputs produce a "negative" result, such a no launch.
The inputs are invalid. This could mean that the input to a function does not have enough elements in an array (or too many), or the array is empty or of the wrong type.

**Comment by gustafssonlinnea** [comment]
Blocked by many issues :)
